#!/usr/bin/env python3
"""
prepare_clearance.py — Pre-compute eclipse sun clearance raster.

For each grid point within the totality path, computes the terrain horizon
angle in the sun's direction and the resulting clearance margin (sun_alt
minus horizon_angle).  Output as tiled PNGs suitable for web map overlay.

ENCODING
--------
Grayscale uint8 PNG, one pixel per grid cell.
  pixel_value = clamp(round((margin_deg + 12.8) * 10), 0, 255)
  128 = exactly 0° clearance (sun touches horizon)
  > 128 = sun clears horizon (green in overlay)
  < 128 = sun blocked (red in overlay)
  Resolution: 0.1° per step, range -12.8° to +12.7°

USAGE
-----
    python prepare_clearance.py                        # default: terrain + canopy
    python prepare_clearance.py --resolution 50 -j 4   # 50m grid, 4 parallel workers
    python prepare_clearance.py --no-canopy             # terrain only
    python prepare_clearance.py --canopy-dir path/to/canopy_tiles
    python prepare_clearance.py --output-dir clearance_tiles

CANOPY DATA
-----------
Reads pre-generated canopy tiles from canopy_tiles/ directory (produced by
prepare_canopy.py).  These are grayscale uint8 PNGs where pixel = tree height
in metres.  No rasterio or network access needed.  Use --no-canopy to skip.

Eclipse Predictions by Fred Espenak, NASA's GSFC.
"""

import argparse
import gzip
import json
import math
import sys
import time
from pathlib import Path

import numpy as np
import requests

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------
EARTH_RADIUS_M = 6_371_000.0
REFRACTION_K = 0.13
SRTM_CACHE = Path("srtm_cache")
CANOPY_TILES_DIR = Path("canopy_tiles")


# ---------------------------------------------------------------------------
# Local canopy tile loading (pre-generated by prepare_canopy.py)
# ---------------------------------------------------------------------------
# Canopy tiles are grayscale uint8 PNGs: pixel value = tree height in metres.
# Each tile covers 1°×1°, named canopy_{lat}_{lon}.png.
# Metadata in tiles.json lists available tiles with max_h, dimensions, etc.

def load_canopy_meta(canopy_dir: Path) -> dict | None:
    """Load canopy tiles.json metadata. Returns dict or None."""
    meta_path = canopy_dir / "tiles.json"
    if not meta_path.exists():
        return None
    return json.loads(meta_path.read_text())


def build_canopy_mosaic(lat_min: float, lat_max: float,
                        lon_min: float, lon_max: float,
                        canopy_dir: Path = CANOPY_TILES_DIR,
                        ) -> tuple[np.ndarray, float, float, float, float] | None:
    """
    Build a canopy height mosaic from local pre-generated tiles.

    Returns (mosaic, lat_min, lat_max, lon_min, lon_max) where mosaic is a
    float32 array of tree heights in metres, or None if no tiles found.
    """
    from PIL import Image

    meta = load_canopy_meta(canopy_dir)
    if meta is None:
        print(f"    Canopy: no tiles.json found in {canopy_dir}", flush=True)
        return None

    # Build index of available tiles
    tile_index = {}
    for t in meta.get("tiles", []):
        tile_index[(t["lat"], t["lon"])] = t

    # Snap bounds to integer degrees (tile boundaries)
    ila_min = int(math.floor(lat_min))
    ila_max = int(math.floor(lat_max))
    ilo_min = int(math.floor(lon_min))
    ilo_max = int(math.floor(lon_max))

    # Collect tiles that overlap the requested region
    loaded = 0
    tile_arrays = {}  # (lat, lon) -> numpy array

    for la in range(ila_min, ila_max + 1):
        for lo in range(ilo_min, ilo_max + 1):
            key = (la, lo)
            if key not in tile_index:
                continue
            t = tile_index[key]
            fpath = canopy_dir / t["file"]
            if not fpath.exists():
                continue
            try:
                img = np.array(Image.open(fpath), dtype=np.float32)
                tile_arrays[key] = img
                loaded += 1
            except Exception as e:
                print(f"    Warning: could not load {fpath}: {e}", flush=True)

    if loaded == 0:
        print(f"    Canopy: no tiles found for region "
              f"lat [{ila_min},{ila_max}] lon [{ilo_min},{ilo_max}]", flush=True)
        return None

    # Build mosaic: uniform grid covering the requested bounds
    # Use the tile pixel density to set mosaic resolution
    sample_key = next(iter(tile_arrays))
    sample_arr = tile_arrays[sample_key]
    px_per_deg_lat = sample_arr.shape[0]  # rows per 1° tile
    px_per_deg_lon = sample_arr.shape[1]  # cols per 1° tile

    n_deg_lat = ila_max - ila_min + 1
    n_deg_lon = ilo_max - ilo_min + 1
    mos_rows = n_deg_lat * px_per_deg_lat
    mos_cols = n_deg_lon * px_per_deg_lon
    mosaic = np.zeros((mos_rows, mos_cols), dtype=np.float32)

    for (la, lo), arr in tile_arrays.items():
        # Row 0 of mosaic = northernmost, so highest lat goes first
        r_off = (ila_max - la) * px_per_deg_lat
        c_off = (lo - ilo_min) * px_per_deg_lon

        # Handle tiles with slightly different dimensions
        h = min(arr.shape[0], mos_rows - r_off)
        w = min(arr.shape[1], mos_cols - c_off)
        if h > 0 and w > 0:
            # Tile images have row 0 = north (top), matching mosaic convention
            mosaic[r_off:r_off + h, c_off:c_off + w] = arr[:h, :w]

    actual_lat_min = float(ila_min)
    actual_lat_max = float(ila_max + 1)
    actual_lon_min = float(ilo_min)
    actual_lon_max = float(ilo_max + 1)

    max_h = mosaic.max()
    print(f"    Canopy: loaded {loaded} tiles, "
          f"{mos_rows}×{mos_cols} px, max height {max_h:.0f}m", flush=True)

    return mosaic, actual_lat_min, actual_lat_max, actual_lon_min, actual_lon_max


def sample_canopy(canopy_mosaic: np.ndarray,
                  lats: np.ndarray, lons: np.ndarray,
                  c_lat_min: float, c_lat_max: float,
                  c_lon_min: float, c_lon_max: float) -> np.ndarray:
    """Sample canopy heights for arrays of lat/lon. Returns heights in metres."""
    n_rows, n_cols = canopy_mosaic.shape
    # Row 0 = north = lat_max
    rows = (c_lat_max - lats) / (c_lat_max - c_lat_min) * (n_rows - 1)
    cols = (lons - c_lon_min) / (c_lon_max - c_lon_min) * (n_cols - 1)

    r = np.clip(np.round(rows).astype(np.int32), 0, n_rows - 1)
    c = np.clip(np.round(cols).astype(np.int32), 0, n_cols - 1)

    return canopy_mosaic[r, c]

# Reuse the eclipse path table from eclipse_horizon.py
ECLIPSE_PATH_TABLE = [
    {"ut": 17.70, "c_lat": 67.21, "c_lon": -26.03, "n_lat": 67.67, "n_lon": -22.71, "s_lat": 66.71, "s_lon": -29.13, "alt": 26, "az": 246, "width": 291, "dur": 138.1},
    {"ut": 17.77, "c_lat": 65.17, "c_lon": -25.21, "n_lat": 65.59, "n_lon": -22.12, "s_lat": 64.71, "s_lon": -28.11, "alt": 26, "az": 248, "width": 294, "dur": 138.2},
    {"ut": 17.83, "c_lat": 63.17, "c_lon": -24.29, "n_lat": 63.56, "n_lon": -21.38, "s_lat": 62.75, "s_lon": -27.03, "alt": 26, "az": 251, "width": 298, "dur": 137.9},
    {"ut": 17.90, "c_lat": 61.20, "c_lon": -23.28, "n_lat": 61.55, "n_lon": -20.51, "s_lat": 60.82, "s_lon": -25.91, "alt": 25, "az": 254, "width": 302, "dur": 137.1},
    {"ut": 17.97, "c_lat": 59.25, "c_lon": -22.17, "n_lat": 59.55, "n_lon": -19.50, "s_lat": 58.90, "s_lon": -24.71, "alt": 25, "az": 257, "width": 305, "dur": 136.0},
    {"ut": 18.03, "c_lat": 57.30, "c_lon": -20.95, "n_lat": 57.57, "n_lon": -18.35, "s_lat": 56.99, "s_lon": -23.42, "alt": 24, "az": 260, "width": 309, "dur": 134.5},
    {"ut": 18.10, "c_lat": 55.34, "c_lon": -19.59, "n_lat": 55.57, "n_lon": -17.03, "s_lat": 55.08, "s_lon": -22.03, "alt": 23, "az": 263, "width": 313, "dur": 132.5},
    {"ut": 18.17, "c_lat": 53.37, "c_lon": -18.06, "n_lat": 53.55, "n_lon": -15.50, "s_lat": 53.15, "s_lon": -20.49, "alt": 22, "az": 266, "width": 316, "dur": 130.0},
    {"ut": 18.23, "c_lat": 51.36, "c_lon": -16.30, "n_lat": 51.48, "n_lon": -13.71, "s_lat": 51.19, "s_lon": -18.76, "alt": 20, "az": 269, "width": 319, "dur": 127.0},
    {"ut": 18.30, "c_lat": 49.29, "c_lon": -14.24, "n_lat": 49.33, "n_lon": -11.55, "s_lat": 49.18, "s_lon": -16.77, "alt": 18, "az": 272, "width": 319, "dur": 123.3},
    {"ut": 18.37, "c_lat": 47.10, "c_lon": -11.72, "n_lat": 47.04, "n_lon":  -8.80, "s_lat": 47.08, "s_lon": -14.40, "alt": 16, "az": 275, "width": 318, "dur": 118.8},
    {"ut": 18.40, "c_lat": 45.94, "c_lon": -10.19, "n_lat": 45.80, "n_lon":  -7.08, "s_lat": 45.98, "s_lon": -13.01, "alt": 14, "az": 277, "width": 315, "dur": 116.1},
    {"ut": 18.43, "c_lat": 44.71, "c_lon":  -8.40, "n_lat": 44.46, "n_lon":  -4.95, "s_lat": 44.83, "s_lon": -11.42, "alt": 13, "az": 278, "width": 311, "dur": 113.0},
    {"ut": 18.47, "c_lat": 43.37, "c_lon":  -6.19, "n_lat": 42.91, "n_lon":  -2.09, "s_lat": 43.61, "s_lon":  -9.55, "alt": 10, "az": 281, "width": 304, "dur": 109.3},
    {"ut": 18.50, "c_lat": 41.82, "c_lon":  -3.19, "n_lat": 40.67, "n_lon":   3.30, "s_lat": 42.26, "s_lon":  -7.24, "alt":  8, "az": 283, "width": 294, "dur": 104.6},
    {"ut": 18.53, "c_lat": 39.41, "c_lon":   2.95, "n_lat": 39.71, "n_lon":   6.34, "s_lat": 40.68, "s_lon":  -4.04, "alt":  2, "az": 288, "width": 270, "dur":  95.8},
    # Sunset terminator
    {"ut": 18.53, "c_lat": 38.68, "c_lon":   5.42, "n_lat": 39.71, "n_lon":   6.34, "s_lat": 37.69, "s_lon":   4.54, "alt":  0, "az": 290, "width": 262, "dur":  92.8},
]


# ---------------------------------------------------------------------------
# Point-in-polygon for eclipse path
# ---------------------------------------------------------------------------
_eclipse_poly: list[tuple[float, float]] | None = None


def _get_eclipse_poly() -> list[tuple[float, float]]:
    global _eclipse_poly
    if _eclipse_poly is None:
        north = [(r["n_lat"], r["n_lon"]) for r in ECLIPSE_PATH_TABLE]
        south = [(r["s_lat"], r["s_lon"]) for r in ECLIPSE_PATH_TABLE]
        _eclipse_poly = north + south[::-1]
    return _eclipse_poly


def point_in_path(lat: float, lon: float) -> bool:
    poly = _get_eclipse_poly()
    inside = False
    n = len(poly)
    j = n - 1
    for i in range(n):
        yi, xi = poly[i]
        yj, xj = poly[j]
        if ((yi > lat) != (yj > lat)) and \
           (lon < (xj - xi) * (lat - yi) / (yj - yi) + xi):
            inside = not inside
        j = i
    return inside


def points_in_path_vec(lats: np.ndarray, lons: np.ndarray) -> np.ndarray:
    """Vectorized ray-casting point-in-polygon test.
    lats and lons are 1D arrays. Returns bool array."""
    poly = _get_eclipse_poly()
    n = len(poly)
    inside = np.zeros(len(lats), dtype=bool)

    yj, xj = poly[-1]
    for i in range(n):
        yi, xi = poly[i]
        # Vectorized crossing test
        cond1 = (yi > lats) != (yj > lats)
        with np.errstate(divide='ignore', invalid='ignore'):
            x_cross = (xj - xi) * (lats - yi) / (yj - yi) + xi
        cond2 = lons < x_cross
        inside ^= (cond1 & cond2)
        yj, xj = yi, xi

    return inside


def tile_overlaps_path(lat: int, lon: int) -> bool:
    """Check if any corner or center of a 1° tile falls within the path."""
    points = [
        (lat + 0.5, lon + 0.5),  # center
        (lat, lon), (lat + 1, lon), (lat, lon + 1), (lat + 1, lon + 1),  # corners
        (lat + 0.5, lon), (lat + 0.5, lon + 1),  # edge midpoints
        (lat, lon + 0.5), (lat + 1, lon + 0.5),
    ]
    return any(point_in_path(la, lo) for la, lo in points)


# ---------------------------------------------------------------------------
# Eclipse circumstances (interpolation from path table)
# ---------------------------------------------------------------------------
def _pt_to_seg_dist(px: float, py: float,
                    ax: float, ay: float,
                    bx: float, by: float) -> tuple[float, float]:
    mid_lat = math.radians((ay + by + py) / 3)
    k_lat = 111.32
    k_lon = 111.32 * math.cos(mid_lat)
    pxk, pyk = px * k_lon, py * k_lat
    axk, ayk = ax * k_lon, ay * k_lat
    bxk, byk = bx * k_lon, by * k_lat
    dx, dy = bxk - axk, byk - ayk
    s2 = dx * dx + dy * dy
    if s2 < 1e-12:
        return math.hypot(pxk - axk, pyk - ayk), 0.0
    t = max(0.0, min(1.0, ((pxk - axk) * dx + (pyk - ayk) * dy) / s2))
    return math.hypot(pxk - (axk + t * dx), pyk - (ayk + t * dy)), t


def get_sun_position(lat: float, lon: float) -> tuple[float, float]:
    """Return (sun_altitude_deg, sun_azimuth_deg) during totality for a location."""
    table = ECLIPSE_PATH_TABLE
    best_dist = float("inf")
    best_i = 0
    best_t = 0.0
    for i in range(len(table) - 1):
        a, b = table[i], table[i + 1]
        d, t = _pt_to_seg_dist(lon, lat, a["c_lon"], a["c_lat"],
                                b["c_lon"], b["c_lat"])
        if d < best_dist:
            best_dist, best_i, best_t = d, i, t

    a, b = table[best_i], table[best_i + 1]
    lerp = lambda k: a[k] + best_t * (b[k] - a[k])

    c_lat = lerp("c_lat")
    sun_alt = lerp("alt") + (lat - c_lat) * 0.15
    sun_az = lerp("az")
    return max(0.5, sun_alt), sun_az


def get_sun_positions_vec(lats: np.ndarray, lons: np.ndarray) -> tuple[np.ndarray, np.ndarray]:
    """Vectorized sun position for arrays of lat/lon.
    Returns (altitudes, azimuths) arrays."""
    table = ECLIPSE_PATH_TABLE
    n_seg = len(table) - 1
    n_pts = len(lats)

    # For each point, find nearest centerline segment
    best_dist = np.full(n_pts, np.inf)
    best_i = np.zeros(n_pts, dtype=np.int32)
    best_t = np.zeros(n_pts)

    for i in range(n_seg):
        a, b = table[i], table[i + 1]
        # Vectorized point-to-segment distance
        mid_lat = np.radians((a["c_lat"] + b["c_lat"] + lats) / 3)
        k_lat = 111.32
        k_lon = 111.32 * np.cos(mid_lat)

        pxk = lons * k_lon
        pyk = lats * k_lat
        axk = a["c_lon"] * k_lon
        ayk = a["c_lat"] * k_lat
        bxk = b["c_lon"] * k_lon
        byk = b["c_lat"] * k_lat

        dx = bxk - axk
        dy = byk - ayk
        s2 = dx * dx + dy * dy
        s2 = np.where(s2 < 1e-12, 1e-12, s2)
        t = np.clip(((pxk - axk) * dx + (pyk - ayk) * dy) / s2, 0, 1)
        d = np.hypot(pxk - (axk + t * dx), pyk - (ayk + t * dy))

        mask = d < best_dist
        best_dist = np.where(mask, d, best_dist)
        best_i = np.where(mask, i, best_i)
        best_t = np.where(mask, t, best_t)

    # Interpolate sun position for each point
    sun_alts = np.zeros(n_pts)
    sun_azs = np.zeros(n_pts)

    for i in range(n_seg):
        seg_mask = best_i == i
        if not seg_mask.any():
            continue
        a, b = table[i], table[i + 1]
        t = best_t[seg_mask]
        c_lat = a["c_lat"] + t * (b["c_lat"] - a["c_lat"])
        alt = a["alt"] + t * (b["alt"] - a["alt"])
        az = a["az"] + t * (b["az"] - a["az"])
        sun_alts[seg_mask] = np.maximum(0.5, alt + (lats[seg_mask] - c_lat) * 0.15)
        sun_azs[seg_mask] = az

    return sun_alts, sun_azs


# ---------------------------------------------------------------------------
# SRTM tile loading
# ---------------------------------------------------------------------------
def tile_filename(lat: int, lon: int) -> str:
    ns = "N" if lat >= 0 else "S"
    ew = "E" if lon >= 0 else "W"
    return f"{ns}{abs(lat):02d}{ew}{abs(lon):03d}.hgt"


def download_tile(lat: int, lon: int, cache_dir: Path) -> Path:
    cache_dir.mkdir(parents=True, exist_ok=True)
    fname = tile_filename(lat, lon)
    local_path = cache_dir / fname

    if local_path.exists() and local_path.stat().st_size > 1_000_000:
        return local_path

    ns = "N" if lat >= 0 else "S"
    tile_name = f"{ns}{abs(lat):02d}{'E' if lon >= 0 else 'W'}{abs(lon):03d}"
    urls = [
        f"https://opentopography.s3.sdsc.edu/raster/SRTM_GL1/SRTM_GL1_srtm/{tile_name}.hgt",
        f"https://s3.amazonaws.com/elevation-tiles-prod/skadi/{ns}{abs(lat):02d}/{tile_name}.hgt.gz",
    ]

    for url in urls:
        print(f"    Downloading {fname} ...", end=" ", flush=True)
        try:
            r = requests.get(url, timeout=120, stream=True)
            if r.status_code != 200:
                print(f"HTTP {r.status_code}")
                continue
            data = r.content
            if url.endswith(".gz"):
                data = gzip.decompress(data)
            local_path.write_bytes(data)
            print(f"OK ({len(data) / 1e6:.1f} MB)")
            return local_path
        except Exception as e:
            print(f"failed ({e})")

    raise FileNotFoundError(f"Could not download {fname}")


def load_srtm_tile(lat: int, lon: int, cache_dir: Path) -> np.ndarray | None:
    """Load a single SRTM tile, returns 3601×3601 int16 array or None."""
    try:
        path = download_tile(lat, lon, cache_dir)
        data = np.frombuffer(path.read_bytes(), dtype=">i2")
        side = int(math.sqrt(len(data)))
        return data.reshape((side, side))
    except (FileNotFoundError, ValueError):
        return None


def build_mosaic(lat_min: int, lat_max: int,
                 lon_min: int, lon_max: int,
                 cache_dir: Path) -> tuple[np.ndarray, int, int, int]:
    """
    Build a contiguous elevation mosaic from SRTM tiles.

    Returns (mosaic, lat_min, lon_min, tile_side) where mosaic is a float32
    array covering [lat_min, lat_max+1] × [lon_min, lon_max+1].
    """
    # Determine tile resolution from first available tile
    tile_side = 3601  # SRTM1 default
    n_lat = lat_max - lat_min + 1
    n_lon = lon_max - lon_min + 1
    rows = n_lat * (tile_side - 1) + 1
    cols = n_lon * (tile_side - 1) + 1

    mosaic = np.zeros((rows, cols), dtype=np.float32)

    for la in range(lat_min, lat_max + 1):
        for lo in range(lon_min, lon_max + 1):
            tile = load_srtm_tile(la, lo, cache_dir)
            if tile is None:
                continue
            tile_side = tile.shape[0]
            # Position in mosaic: top-left corner
            # SRTM rows go from north to south (top = lat+1, bottom = lat)
            r_off = (lat_max - la) * (tile_side - 1)
            c_off = (lo - lon_min) * (tile_side - 1)
            h = tile.shape[0]
            w = tile.shape[1]
            mosaic[r_off:r_off + h, c_off:c_off + w] = tile.astype(np.float32)

    # Replace voids
    mosaic[mosaic < -500] = 0.0

    return mosaic, lat_min, lon_min, tile_side


def sample_mosaic(mosaic: np.ndarray,
                  lats: np.ndarray, lons: np.ndarray,
                  mos_lat_min: int, mos_lon_min: int,
                  mos_lat_max: int, tile_side: int) -> np.ndarray:
    """
    Bilinear-interpolated elevation lookup for arrays of lat/lon.
    Returns elevations in metres.
    """
    n = tile_side - 1  # pixels per degree

    # Convert to mosaic pixel coordinates
    # Row 0 = top = lat_max + 1, increasing row = decreasing lat
    rows = (mos_lat_max + 1 - lats) * n
    cols = (lons - mos_lon_min) * n

    r0 = np.clip(np.floor(rows).astype(np.int32), 0, mosaic.shape[0] - 2)
    c0 = np.clip(np.floor(cols).astype(np.int32), 0, mosaic.shape[1] - 2)
    dr = np.clip(rows - r0, 0, 1)
    dc = np.clip(cols - c0, 0, 1)

    z00 = mosaic[r0, c0]
    z01 = mosaic[r0, c0 + 1]
    z10 = mosaic[r0 + 1, c0]
    z11 = mosaic[r0 + 1, c0 + 1]

    return z00 * (1 - dr) * (1 - dc) + z01 * (1 - dr) * dc + \
           z10 * dr * (1 - dc) + z11 * dr * dc


# ---------------------------------------------------------------------------
# Vectorized ray-march for clearance computation
# ---------------------------------------------------------------------------
def compute_clearance_tile(tile_lat: int, tile_lon: int,
                           resolution_m: float = 250.0,
                           max_ray_m: float = 50_000.0,
                           ray_step_m: float = 90.0,
                           observer_h: float = 2.0,
                           cache_dir: Path = SRTM_CACHE,
                           use_canopy: bool = True,
                           canopy_dir: Path = CANOPY_TILES_DIR,
                           ) -> np.ndarray | None:
    """
    Compute clearance margin for every grid point in a 1°×1° tile.

    When use_canopy is True, tree heights from local canopy tiles are
    added to terrain elevations along each ray, giving the effective
    horizon including canopy obstruction.

    Returns a 2D float32 array of margin values in degrees, or None if
    the tile doesn't overlap the eclipse path.
    """
    if not tile_overlaps_path(tile_lat, tile_lon):
        return None

    # Grid dimensions
    lat_span_m = 111_320.0  # metres per degree latitude
    lon_span_m = 111_320.0 * math.cos(math.radians(tile_lat + 0.5))

    n_rows = max(2, int(lat_span_m / resolution_m))
    n_cols = max(2, int(lon_span_m / resolution_m))

    # Grid point coordinates (cell centres)
    dlat = 1.0 / n_rows
    dlon = 1.0 / n_cols
    lats_1d = np.linspace(tile_lat + dlat / 2, tile_lat + 1 - dlat / 2, n_rows)
    lons_1d = np.linspace(tile_lon + dlon / 2, tile_lon + 1 - dlon / 2, n_cols)
    # lats_1d goes south to north; we'll flip at the end for image convention
    grid_lons, grid_lats = np.meshgrid(lons_1d, lats_1d)  # shape (n_rows, n_cols)

    # Vectorized in-path mask
    flat_all_lats = grid_lats.ravel()
    flat_all_lons = grid_lons.ravel()
    in_path_flat = points_in_path_vec(flat_all_lats, flat_all_lons)
    in_path = in_path_flat.reshape(n_rows, n_cols)

    n_active = in_path.sum()
    if n_active == 0:
        return None

    print(f"  Grid: {n_rows}×{n_cols} = {n_rows * n_cols} pts, "
          f"{n_active} inside path", flush=True)

    # Vectorized sun positions for active points
    flat_lats = grid_lats[in_path]
    flat_lons = grid_lons[in_path]
    sun_alts_flat, sun_azs_flat = get_sun_positions_vec(flat_lats, flat_lons)

    # Use median azimuth for ray direction (varies <2° across a tile)
    sun_az_median = float(np.median(sun_azs_flat))
    az_rad = math.radians(sun_az_median)

    # Load SRTM mosaic with buffer for rays
    buf_deg = max_ray_m / 111_320.0 + 0.5
    mos_lat_min = int(math.floor(tile_lat - buf_deg))
    mos_lat_max = int(math.floor(tile_lat + 1 + buf_deg))
    mos_lon_min = int(math.floor(tile_lon - buf_deg))
    mos_lon_max = int(math.floor(tile_lon + 1 + buf_deg))

    print(f"  Loading SRTM mosaic: lat [{mos_lat_min}, {mos_lat_max}], "
          f"lon [{mos_lon_min}, {mos_lon_max}] ...", flush=True)
    mosaic, _, _, tile_side = build_mosaic(
        mos_lat_min, mos_lat_max, mos_lon_min, mos_lon_max, cache_dir)

    # Load canopy mosaic (covers same extent as SRTM buffer)
    canopy_data = None
    if use_canopy:
        print(f"  Loading canopy data ...", flush=True)
        canopy_result = build_canopy_mosaic(
            mos_lat_min, mos_lat_max + 1,
            mos_lon_min, mos_lon_max + 1,
            canopy_dir=canopy_dir,
        )
        if canopy_result is not None:
            canopy_data = canopy_result

    # Observer elevations (flat_lats, flat_lons already defined above)
    obs_elevs = sample_mosaic(mosaic, flat_lats, flat_lons,
                              mos_lat_min, mos_lon_min, mos_lat_max, tile_side)
    obs_elevs += observer_h

    # Ray-march: step along sun azimuth, track max elevation angle
    max_angles = np.full(n_active, -90.0, dtype=np.float32)
    n_steps = int(max_ray_m / ray_step_m)

    # Precompute lat/lon offsets per step (same for all points — same azimuth)
    cos_az = math.cos(az_rad)
    sin_az = math.sin(az_rad)
    mean_lat_rad = math.radians(tile_lat + 0.5)
    m_per_deg_lat = 111_320.0
    m_per_deg_lon = 111_320.0 * math.cos(mean_lat_rad)

    print(f"  Ray-marching {n_active} points × {n_steps} steps "
          f"(az={sun_az_median:.1f}°) ...", flush=True)
    t0 = time.time()

    for step in range(1, n_steps + 1):
        d = step * ray_step_m

        # Earth curvature + refraction correction
        curvature_m = (d * d) / (2 * EARTH_RADIUS_M * (1 - REFRACTION_K))

        # Target positions
        dlat_deg = d * cos_az / m_per_deg_lat
        dlon_deg = d * sin_az / m_per_deg_lon
        tgt_lats = flat_lats + dlat_deg
        tgt_lons = flat_lons + dlon_deg

        # Sample elevations
        tgt_elevs = sample_mosaic(mosaic, tgt_lats, tgt_lons,
                                  mos_lat_min, mos_lon_min, mos_lat_max, tile_side)

        # Add canopy heights if available
        if canopy_data is not None:
            cm, c_lat_min, c_lat_max, c_lon_min, c_lon_max = canopy_data
            tree_h = sample_canopy(cm, tgt_lats, tgt_lons,
                                   c_lat_min, c_lat_max, c_lon_min, c_lon_max)
            tgt_elevs += tree_h

        # Elevation angle from observer
        elev_diff = tgt_elevs - obs_elevs - curvature_m
        angles = np.degrees(np.arctan2(elev_diff, d))

        # Track max
        np.maximum(max_angles, angles, out=max_angles)

        if step % 100 == 0:
            print(f"\r    step {step}/{n_steps} "
                  f"({step * ray_step_m / 1000:.0f} km) ...", end="", flush=True)

    elapsed = time.time() - t0
    print(f"\r    {n_steps} steps done in {elapsed:.1f}s"
          f" ({n_active * n_steps / elapsed / 1e6:.1f}M lookups/s)    ")

    # Compute margins
    flat_margins = sun_alts_flat - max_angles

    # Sea fix: SRTM ocean = 0m elevation. Points at/below sea level are open
    # ocean with no terrain obstructions — force a large positive margin to
    # prevent false red artifacts from coastal features along the ray.
    ground_elevs = obs_elevs - observer_h  # undo observer height to get ground
    sea_mask = ground_elevs <= 1.0
    if sea_mask.any():
        flat_margins[sea_mask] = 15.0  # guaranteed clear from open ocean
        n_sea = sea_mask.sum()
        print(f"    Sea fix: {n_sea} ocean points forced visible "
              f"({n_sea / n_active * 100:.0f}%)")

    # Assemble result grid (NaN for outside-path points)
    margin_grid = np.full((n_rows, n_cols), np.nan, dtype=np.float32)
    margin_grid[in_path] = flat_margins

    # Flip vertically: row 0 = north (image convention)
    margin_grid = margin_grid[::-1, :]

    return margin_grid


def encode_margin_png(margin: np.ndarray, path: Path) -> int:
    """Encode margin array as uint8 PNG. Returns file size in bytes."""
    from PIL import Image

    # Encode: value = (margin + 12.8) * 10, clamped to [0, 255]
    encoded = np.clip(np.round((margin + 12.8) * 10), 0, 255)
    # NaN → 0 (transparent in overlay)
    encoded = np.where(np.isnan(margin), 0, encoded).astype(np.uint8)

    img = Image.fromarray(encoded, mode="L")
    img.save(path, optimize=True)
    return path.stat().st_size


def generate_overview(full_path: Path, overview_path: Path,
                      scale: int = 8) -> int:
    """Downsample a clearance PNG by `scale` factor for fast map preview.
    Returns file size in bytes."""
    from PIL import Image

    img = Image.open(full_path)
    new_w = max(1, img.width // scale)
    new_h = max(1, img.height // scale)
    # Use NEAREST to preserve encoded margin values (not interpolate)
    small = img.resize((new_w, new_h), Image.NEAREST)
    small.save(overview_path, optimize=True)
    return overview_path.stat().st_size


def _process_tile(lat_lon: tuple[int, int], kwargs: dict) -> dict | None:
    """Process a single clearance tile. Module-level for multiprocessing."""
    lat, lon = lat_lon
    label = f"clearance_{lat}_{lon}"
    print(f"\n[{label}] Processing ...", flush=True)
    t0 = time.time()

    margin = compute_clearance_tile(
        lat, lon,
        resolution_m=kwargs["resolution_m"],
        max_ray_m=kwargs["max_ray_m"],
        ray_step_m=kwargs["ray_step_m"],
        observer_h=kwargs["observer_h"],
        cache_dir=kwargs["cache_dir"],
        use_canopy=kwargs["use_canopy"],
        canopy_dir=kwargs["canopy_dir"],
    )

    if margin is None:
        print(f"  → skipped (no points inside path)")
        return None

    fname = f"{label}.png"
    fpath = kwargs["output_dir"] / fname
    fsize = encode_margin_png(margin, fpath)

    # Generate low-res overview for fast map browsing
    overview_dir = kwargs["output_dir"] / "overview"
    overview_dir.mkdir(exist_ok=True)
    ov_path = overview_dir / fname
    ov_size = generate_overview(fpath, ov_path, scale=8)

    valid = margin[~np.isnan(margin)]
    tile_info = {
        "lat": lat,
        "lon": lon,
        "file": fname,
        "kb": round(fsize / 1024, 1),
        "overview_kb": round(ov_size / 1024, 1),
        "rows": int(margin.shape[0]),
        "cols": int(margin.shape[1]),
        "margin_min": round(float(valid.min()), 2),
        "margin_max": round(float(valid.max()), 2),
        "margin_mean": round(float(valid.mean()), 2),
        "pct_visible": round(float((valid > 0).sum() / len(valid) * 100), 1),
    }

    elapsed = time.time() - t0
    print(f"  → {fname} ({tile_info['kb']:.0f} KB, "
          f"{tile_info['rows']}×{tile_info['cols']}, "
          f"{elapsed:.1f}s)")
    print(f"    margin: [{tile_info['margin_min']:+.1f}°, "
          f"{tile_info['margin_max']:+.1f}°], "
          f"mean {tile_info['margin_mean']:+.1f}°, "
          f"{tile_info['pct_visible']:.0f}% visible")
    return tile_info


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
def main() -> None:
    parser = argparse.ArgumentParser(
        description="Pre-compute eclipse sun clearance raster tiles",
    )
    parser.add_argument("--resolution", type=float, default=250.0,
                        help="Grid spacing in metres (default 250)")
    parser.add_argument("--max-ray-km", type=float, default=50.0,
                        help="Max ray-march distance in km (default 50)")
    parser.add_argument("--ray-step-m", type=float, default=90.0,
                        help="Ray step size in metres (default 90)")
    parser.add_argument("--observer-height", type=float, default=2.0,
                        help="Observer height above ground in metres (default 2)")
    parser.add_argument("--output-dir", type=str, default="clearance_tiles",
                        help="Output directory (default clearance_tiles)")
    parser.add_argument("--srtm-cache", type=str, default="srtm_cache",
                        help="SRTM cache directory (default srtm_cache)")
    parser.add_argument("--lat-min", type=int, default=37,
                        help="Minimum latitude (default 37)")
    parser.add_argument("--lat-max", type=int, default=44,
                        help="Maximum latitude (default 44)")
    parser.add_argument("--lon-min", type=int, default=-10,
                        help="Minimum longitude (default -10)")
    parser.add_argument("--lon-max", type=int, default=7,
                        help="Maximum longitude (default 7)")
    parser.add_argument("--jobs", "-j", type=int, default=1,
                        help="Parallel tile jobs (default 1, try num CPU cores)")
    parser.add_argument("--no-canopy", action="store_true",
                        help="Disable tree canopy (terrain only)")
    parser.add_argument("--canopy-dir", type=str, default="canopy_tiles",
                        help="Canopy tiles directory (default canopy_tiles)")

    args = parser.parse_args()
    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    cache_dir = Path(args.srtm_cache)
    canopy_dir = Path(args.canopy_dir)

    # Check canopy availability
    canopy_meta = load_canopy_meta(canopy_dir) if not args.no_canopy else None
    use_canopy = canopy_meta is not None and not args.no_canopy
    if use_canopy:
        n_tiles = len(canopy_meta.get("tiles", []))
        canopy_label = f"terrain+canopy ({n_tiles} tiles from {canopy_dir})"
    elif args.no_canopy:
        canopy_label = "terrain only (disabled)"
    else:
        canopy_label = f"terrain only (no tiles.json in {canopy_dir})"

    print("=" * 70)
    print("  ECLIPSE CLEARANCE RASTER GENERATOR")
    print(f"  Resolution: {args.resolution:.0f}m | "
          f"Ray: {args.max_ray_km:.0f}km @ {args.ray_step_m:.0f}m steps | "
          f"Observer: {args.observer_height:.1f}m")
    print(f"  Bounds: lat [{args.lat_min}, {args.lat_max}], "
          f"lon [{args.lon_min}, {args.lon_max}] | "
          f"Jobs: {args.jobs}")
    print(f"  Canopy: {canopy_label}")
    print(f"  Output: {output_dir}/")
    print("=" * 70)

    # Build list of tiles to process
    tile_jobs = []
    for lat in range(args.lat_min, args.lat_max + 1):
        for lon in range(args.lon_min, args.lon_max + 1):
            if tile_overlaps_path(lat, lon):
                tile_jobs.append((lat, lon))

    print(f"\n  {len(tile_jobs)} tiles overlap the path")

    tile_list = []
    total_t0 = time.time()

    # Build job arguments
    job_kwargs = {
        "resolution_m": args.resolution,
        "max_ray_m": args.max_ray_km * 1000,
        "ray_step_m": args.ray_step_m,
        "observer_h": args.observer_height,
        "cache_dir": cache_dir,
        "use_canopy": use_canopy,
        "canopy_dir": canopy_dir,
        "output_dir": output_dir,
    }

    if args.jobs > 1:
        from concurrent.futures import ProcessPoolExecutor, as_completed
        print(f"  Using {args.jobs} parallel workers")
        with ProcessPoolExecutor(max_workers=args.jobs) as pool:
            futures = {pool.submit(_process_tile, job, job_kwargs): job
                       for job in tile_jobs}
            for future in as_completed(futures):
                result = future.result()
                if result is not None:
                    tile_list.append(result)
    else:
        for job in tile_jobs:
            result = _process_tile(job, job_kwargs)
            if result is not None:
                tile_list.append(result)

    # Write metadata
    meta = {
        "resolution_m": args.resolution,
        "max_ray_km": args.max_ray_km,
        "ray_step_m": args.ray_step_m,
        "observer_height_m": args.observer_height,
        "includes_canopy": use_canopy,
        "has_overview": True,
        "overview_scale": 8,
        "overview_dir": "overview",
        "encoding": "uint8, value = (margin_deg + 12.8) * 10, 128 = 0°",
        "source": "SRTM GL1 30m" + (" + Meta/WRI Canopy Height" if use_canopy else "")
                  + " + NASA/Espenak eclipse path",
        "tiles": tile_list,
    }
    meta_path = output_dir / "clearance.json"
    meta_path.write_text(json.dumps(meta, indent=2))

    total_elapsed = time.time() - total_t0
    print(f"\n{'=' * 70}")
    print(f"  Done! {len(tile_list)} tiles in {total_elapsed / 60:.1f} minutes")
    print(f"  Metadata: {meta_path}")
    print(f"{'=' * 70}")


if __name__ == "__main__":
    main()
